Release 1.2.0 (#19)
* Update javadocs, Update tests, Update PlaywrightOptions

* Fix failed tests

* Bump com.codeborne:selenide from 7.1.0 to 7.2.0

Bumps [com.codeborne:selenide](https://github.com/selenide/selenide) from 7.1.0 to 7.2.0.
- [Release notes](https://github.com/selenide/selenide/releases)
- [Changelog](https://github.com/selenide/selenide/blob/main/CHANGELOG.md)
- [Commits](https://github.com/selenide/selenide/compare/v7.1.0...v7.2.0)

---
updated-dependencies:
- dependency-name: com.codeborne:selenide
  dependency-type: direct:production
  update-type: version-update:semver-minor
...

Signed-off-by: dependabot[bot] <support@github.com>

* Rebuild Playwrightium options: add capabilities to record video, add capabilities run remotely
Rebuild Playwrightium quit method: add saving of video if needed
Separate tests on local and remote
Rebuild workflow file: divide all on 2 jobs - local and remote
Update tests

* Fix to run builds for every push

* Fix to run builds for every push

* Fix to run builds for every push

* Fix to run builds for every push

* Fix to run builds for every push

* Fix to run builds for every push

* Update README.md

* Update CHANGELOG.md

* Update javadocs, Update tests, Update PlaywrightOptions

* Fix failed tests

* Rebuild Playwrightium options: add capabilities to record video, add capabilities run remotely
Rebuild Playwrightium quit method: add saving of video if needed
Separate tests on local and remote
Rebuild workflow file: divide all on 2 jobs - local and remote
Update tests

* Fix to run builds for every push

* Fix to run builds for every push

* Fix to run builds for every push

* Fix to run builds for every push

* Fix to run builds for every push

* Fix to run builds for every push

* Update README.md

* Update CHANGELOG.md

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -1,7 +1,8 @@
-name: Playwright Tests
+name: Playwrightium Tests
 on:
   push:
-    branches: [ main, master ]
+    branches:
+      - '**'
   pull_request:
     branches: [ main, master ]
 permissions:
@@ -9,13 +10,13 @@ permissions:
   actions: read
   checks: write
 jobs:
-  playwright:
+  playwrightium_local:
     env:
       DISPLAY: :0
-    name: 'Playwright Tests'
+    name: 'Playwrightuim local Tests'
     runs-on: ubuntu-latest
     container:
-      image: mcr.microsoft.com/playwright/java:v1.40.0-jammy
+      image: mcr.microsoft.com/playwright/java:v1.41.2-jammy
     steps:
       - uses: actions/checkout@v4
       - uses: actions/setup-java@v4
@@ -23,12 +24,41 @@ jobs:
           distribution: 'temurin'
           java-version: '17'
       - name: Build & Install
-        run: mvn -B install -D skipTests --no-transfer-progress
+        run: mvn -B install -DskipTests --no-transfer-progress
       - name: Run tests
-        run: xvfb-run mvn test
+        run: xvfb-run mvn test -Dtest=org.brit.test.selenide.local.**.*
       - name: Publish Test Report
         uses: mikepenz/action-junit-report@v4
         if: success() || failure() # always run even if the previous step fails
         with:
+          check_name: 'Playwrightium local tests results'
+          report_paths: '**/target/surefire-reports/TEST-*.xml'
+          include_passed: true
+  playwrightium_selenoid:
+    name: 'Playwrightium remote tests'
+    runs-on: ubuntu-latest
+#    container:
+#      image: mcr.microsoft.com/playwright/java:v1.41.2-jammy
+    steps:
+      - name: Start selenoid
+        uses: Xotabu4/selenoid-github-action@v2
+      - uses: actions/checkout@v4
+      - uses: actions/setup-java@v4
+        with:
+          distribution: 'temurin'
+          java-version: '17'
+      - name: Setup Maven Action
+        uses: s4u/setup-maven-action@v1.12.0
+      - name: install playwright
+        run:  mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install"
+      - name: Build & Install
+        run: mvn -B install -DskipTests --no-transfer-progress
+      - name: Run tests
+        run: mvn test -Dtest=org.brit.test.selenide.remote.**.*
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          check_name: 'Playwrightium remote tests results'
           report_paths: '**/target/surefire-reports/TEST-*.xml'
           include_passed: true
