Add upload artifacts option to workflow file

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -35,48 +35,40 @@ jobs:
           check_name: 'Playwrightium local tests results'
           report_paths: '**/target/surefire-reports/TEST-*.xml'
           include_passed: true
-      - uses: actions/upload-artifact@v2
+      - name: View images folder
+        run: ls target/reports/
+      - name: Upload images
+        uses: actions/upload-artifact@v2
         if: always()
         with:
           name: Images
-          path: |
-            build/reports/
-            target/reports/
+          path: ~/target/reports/
           retention-days: 15
-  playwrightium_selenoid:
-    name: 'Playwrightium remote tests'
-    runs-on: ubuntu-latest
-    #    container:
-    #      image: mcr.microsoft.com/playwright/java:v1.41.2-jammy
-    steps:
-      - name: Start selenoid
-        uses: Xotabu4/selenoid-github-action@v2
-      - uses: actions/checkout@v4
-      - uses: actions/setup-java@v4
-        with:
-          distribution: 'temurin'
-          java-version: '17'
-      - name: Setup Maven Action
-        uses: s4u/setup-maven-action@v1.12.0
-      - name: install playwright
-        run: mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install"
-      - name: Build & Install
-        run: mvn -B install -DskipTests --no-transfer-progress
-      - name: Run tests
-        run: mvn test -Dtest=org.brit.test.selenide.remote.**.*
-      - name: Publish Test Report
-        uses: mikepenz/action-junit-report@v4
-        if: success() || failure() # always run even if the previous step fails
-        with:
-          check_name: 'Playwrightium remote tests results'
-          report_paths: '**/target/surefire-reports/TEST-*.xml'
-          include_passed: true
-      - uses: actions/upload-artifact@v2
-        if: always()
-        with:
-          name: Images selenoid tests
-          path: |
-            build/reports/
-            target/reports
-          retention-days: 15
-
+#  playwrightium_selenoid:
+#    name: 'Playwrightium remote tests'
+#    runs-on: ubuntu-latest
+#    #    container:
+#    #      image: mcr.microsoft.com/playwright/java:v1.41.2-jammy
+#    steps:
+#      - name: Start selenoid
+#        uses: Xotabu4/selenoid-github-action@v2
+#      - uses: actions/checkout@v4
+#      - uses: actions/setup-java@v4
+#        with:
+#          distribution: 'temurin'
+#          java-version: '17'
+#      - name: Setup Maven Action
+#        uses: s4u/setup-maven-action@v1.12.0
+#      - name: install playwright
+#        run: mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install"
+#      - name: Build & Install
+#        run: mvn -B install -DskipTests --no-transfer-progress
+#      - name: Run tests
+#        run: mvn test -Dtest=org.brit.test.selenide.remote.**.*
+#      - name: Publish Test Report
+#        uses: mikepenz/action-junit-report@v4
+#        if: success() || failure() # always run even if the previous step fails
+#        with:
+#          check_name: 'Playwrightium remote tests results'
+#          report_paths: '**/target/surefire-reports/TEST-*.xml'
+#          include_passed: true
